apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: viewer-test
subjects:
  - kind: ServiceAccount
    name: viewer
roleRef:
  kind: ClusterRole
  name: viewer
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redactor-test
subjects:
  - kind: ServiceAccount
    name: redactor
roleRef:
  kind: ClusterRole
  name: redactor
  apiGroup: rbac.authorization.k8s.io
